#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Feb 26 16:49:24 EST 2020
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim mips_testbench_behav -key {Behavioral:sim_1:Functional:mips_testbench} -tclbatch mips_testbench.tcl -protoinst "protoinst_files/datapath.protoinst" -view /tools/Xilinx/Vivado/2018.3/bin/lab2/mips_testbench_behav.wcfg -log simulate.log
