# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/mips.xdc

# Block Designs: bd/datapath/datapath.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath || ORIG_REF_NAME==datapath} -quiet] -quiet

# IP: bd/datapath/ip/datapath_pc_0_0/datapath_pc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_pc_0_0 || ORIG_REF_NAME==datapath_pc_0_0} -quiet] -quiet

# IP: bd/datapath/ip/datapath_pc_add_0_0/datapath_pc_add_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_pc_add_0_0 || ORIG_REF_NAME==datapath_pc_add_0_0} -quiet] -quiet

# IP: bd/datapath/ip/datapath_instmem_0_0/datapath_instmem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_instmem_0_0 || ORIG_REF_NAME==datapath_instmem_0_0} -quiet] -quiet

# IP: bd/datapath/ip/datapath_regfile_0_0/datapath_regfile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_regfile_0_0 || ORIG_REF_NAME==datapath_regfile_0_0} -quiet] -quiet

# IP: bd/datapath/ip/datapath_control_unit_0_0/datapath_control_unit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_control_unit_0_0 || ORIG_REF_NAME==datapath_control_unit_0_0} -quiet] -quiet

# IP: bd/datapath/ip/datapath_xlslice_0_0/datapath_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_xlslice_0_0 || ORIG_REF_NAME==datapath_xlslice_0_0} -quiet] -quiet

# IP: bd/datapath/ip/datapath_xlslice_1_0/datapath_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_xlslice_1_0 || ORIG_REF_NAME==datapath_xlslice_1_0} -quiet] -quiet

# IP: bd/datapath/ip/datapath_xlslice_2_0/datapath_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_xlslice_2_0 || ORIG_REF_NAME==datapath_xlslice_2_0} -quiet] -quiet

# IP: bd/datapath/ip/datapath_xlslice_3_0/datapath_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_xlslice_3_0 || ORIG_REF_NAME==datapath_xlslice_3_0} -quiet] -quiet

# IP: bd/datapath/ip/datapath_ALU_0_0/datapath_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_ALU_0_0 || ORIG_REF_NAME==datapath_ALU_0_0} -quiet] -quiet

# IP: bd/datapath/ip/datapath_alu_control_0_0/datapath_alu_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_alu_control_0_0 || ORIG_REF_NAME==datapath_alu_control_0_0} -quiet] -quiet

# IP: bd/datapath/ip/datapath_xlslice_4_1/datapath_xlslice_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==datapath_xlslice_4_1 || ORIG_REF_NAME==datapath_xlslice_4_1} -quiet] -quiet

# XDC: bd/datapath/datapath_ooc.xdc
